[pytest]
# Lets the "pytest" command find our "app" and "seed" folders when run from the backend folder.
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
