"""create all tables

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 16:12:01.739309
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_partners',
    sa.Column('firm_name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_partners_created_at'), 'channel_partners', ['created_at'], unique=False)
    op.create_index(op.f('ix_channel_partners_firm_name'), 'channel_partners', ['firm_name'], unique=False)
    op.create_table('contractors',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trade', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_created_at'), 'contractors', ['created_at'], unique=False)
    op.create_index(op.f('ix_contractors_name'), 'contractors', ['name'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_table('payment_plans',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_payment_plans_created_at'), 'payment_plans', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('locality', sa.String(length=80), nullable=False),
    sa.Column('rera_no', sa.String(length=40), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=False),
    sa.Column('expected_possession', sa.Date(), nullable=False),
    sa.Column('total_acres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_type'), 'projects', ['type'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('role_title', sa.String(length=80), nullable=False),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_employees_created_at'), 'employees', ['created_at'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_role_title'), 'employees', ['role_title'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('plan_milestones',
    sa.Column('payment_plan_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('construction_milestone_type', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_milestones_created_at'), 'plan_milestones', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_milestones_payment_plan_id'), 'plan_milestones', ['payment_plan_id'], unique=False)
    op.create_table('price_history',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('config', sa.String(length=20), nullable=False),
    sa.Column('price_psf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_created_at'), 'price_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_history_effective_from'), 'price_history', ['effective_from'], unique=False)
    op.create_index(op.f('ix_price_history_project_id'), 'price_history', ['project_id'], unique=False)
    op.create_table('project_budgets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_budgets_created_at'), 'project_budgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_budgets_project_id'), 'project_budgets', ['project_id'], unique=False)
    op.create_table('safety_incidents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_incidents_created_at'), 'safety_incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_safety_incidents_occurred_on'), 'safety_incidents', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_safety_incidents_project_id'), 'safety_incidents', ['project_id'], unique=False)
    op.create_table('towers',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('units_per_floor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towers_created_at'), 'towers', ['created_at'], unique=False)
    op.create_index(op.f('ix_towers_project_id'), 'towers', ['project_id'], unique=False)
    op.create_table('construction_milestones',
    sa.Column('tower_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('percent_complete', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('owner_employee_id', sa.Uuid(), nullable=True),
    sa.Column('delay_cause', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_milestones_contractor_id'), 'construction_milestones', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_construction_milestones_created_at'), 'construction_milestones', ['created_at'], unique=False)
    op.create_index(op.f('ix_construction_milestones_owner_employee_id'), 'construction_milestones', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_construction_milestones_planned_date'), 'construction_milestones', ['planned_date'], unique=False)
    op.create_index(op.f('ix_construction_milestones_tower_id'), 'construction_milestones', ['tower_id'], unique=False)
    op.create_index(op.f('ix_construction_milestones_type'), 'construction_milestones', ['type'], unique=False)
    op.create_table('employee_targets',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_targets_created_at'), 'employee_targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_employee_targets_employee_id'), 'employee_targets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_targets_period_start'), 'employee_targets', ['period_start'], unique=False)
    op.create_table('leads',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('channel_partner_id', sa.Uuid(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('preferred_config', sa.String(length=20), nullable=True),
    sa.Column('preferred_project_id', sa.Uuid(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('owner_employee_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('lost_reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_partner_id'], ['channel_partners.id'], ),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['preferred_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_channel_partner_id'), 'leads', ['channel_partner_id'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_owner_employee_id'), 'leads', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_leads_preferred_project_id'), 'leads', ['preferred_project_id'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('quality_issues',
    sa.Column('tower_id', sa.Uuid(), nullable=False),
    sa.Column('raised_on', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contractor_id', sa.Uuid(), nullable=True),
    sa.Column('owner_employee_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_contractor_id'), 'quality_issues', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_quality_issues_created_at'), 'quality_issues', ['created_at'], unique=False)
    op.create_index(op.f('ix_quality_issues_owner_employee_id'), 'quality_issues', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_quality_issues_raised_on'), 'quality_issues', ['raised_on'], unique=False)
    op.create_index(op.f('ix_quality_issues_status'), 'quality_issues', ['status'], unique=False)
    op.create_index(op.f('ix_quality_issues_tower_id'), 'quality_issues', ['tower_id'], unique=False)
    op.create_table('risks',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('facts_json', sa.JSON(), nullable=False),
    sa.Column('entity_refs_json', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_employee_id', sa.Uuid(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_category'), 'risks', ['category'], unique=False)
    op.create_index(op.f('ix_risks_created_at'), 'risks', ['created_at'], unique=False)
    op.create_index(op.f('ix_risks_owner_employee_id'), 'risks', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_risks_rule_id'), 'risks', ['rule_id'], unique=False)
    op.create_index(op.f('ix_risks_severity'), 'risks', ['severity'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('owner_employee_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_on'), 'tasks', ['due_on'], unique=False)
    op.create_index(op.f('ix_tasks_owner_employee_id'), 'tasks', ['owner_employee_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('units',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tower_id', sa.Uuid(), nullable=True),
    sa.Column('unit_no', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('config', sa.String(length=20), nullable=False),
    sa.Column('carpet_sft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sba_sft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('plot_sqyd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('facing', sa.String(length=10), nullable=False),
    sa.Column('base_price_psf', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plc_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('floor_rise_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('listed_on', sa.Date(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'unit_no')
    )
    op.create_index(op.f('ix_units_config'), 'units', ['config'], unique=False)
    op.create_index(op.f('ix_units_created_at'), 'units', ['created_at'], unique=False)
    op.create_index(op.f('ix_units_project_id'), 'units', ['project_id'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_index(op.f('ix_units_tower_id'), 'units', ['tower_id'], unique=False)
    op.create_index(op.f('ix_units_unit_no'), 'units', ['unit_no'], unique=False)
    op.create_table('customers',
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_nri', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('rm_employee_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['rm_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_is_nri'), 'customers', ['is_nri'], unique=False)
    op.create_index(op.f('ix_customers_lead_id'), 'customers', ['lead_id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_rm_employee_id'), 'customers', ['rm_employee_id'], unique=False)
    op.create_index(op.f('ix_customers_type'), 'customers', ['type'], unique=False)
    op.create_table('lead_activities',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_activities_created_at'), 'lead_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_activities_employee_id'), 'lead_activities', ['employee_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_occurred_at'), 'lead_activities', ['occurred_at'], unique=False)
    op.create_table('site_visits',
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visits_created_at'), 'site_visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_site_visits_employee_id'), 'site_visits', ['employee_id'], unique=False)
    op.create_index(op.f('ix_site_visits_lead_id'), 'site_visits', ['lead_id'], unique=False)
    op.create_index(op.f('ix_site_visits_project_id'), 'site_visits', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_visits_scheduled_at'), 'site_visits', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_site_visits_status'), 'site_visits', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('channel_partner_id', sa.Uuid(), nullable=True),
    sa.Column('booked_on', sa.Date(), nullable=False),
    sa.Column('agreement_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_reason', sa.String(length=120), nullable=True),
    sa.Column('agreement_on', sa.Date(), nullable=True),
    sa.Column('registered_on', sa.Date(), nullable=True),
    sa.Column('possession_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_partner_id'], ['channel_partners.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booked_on'), 'bookings', ['booked_on'], unique=False)
    op.create_index(op.f('ix_bookings_channel_partner_id'), 'bookings', ['channel_partner_id'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_employee_id'), 'bookings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_plan_id'), 'bookings', ['payment_plan_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_unit_id'), 'bookings', ['unit_id'], unique=False)
    op.create_table('customer_interactions',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('needs_reply', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_created_at'), 'customer_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_employee_id'), 'customer_interactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_needs_reply'), 'customer_interactions', ['needs_reply'], unique=False)
    op.create_index(op.f('ix_customer_interactions_occurred_at'), 'customer_interactions', ['occurred_at'], unique=False)
    op.create_table('interior_projects',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('designer_employee_id', sa.Uuid(), nullable=False),
    sa.Column('package', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['designer_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interior_projects_created_at'), 'interior_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_interior_projects_customer_id'), 'interior_projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interior_projects_designer_employee_id'), 'interior_projects', ['designer_employee_id'], unique=False)
    op.create_index(op.f('ix_interior_projects_stage'), 'interior_projects', ['stage'], unique=False)
    op.create_index(op.f('ix_interior_projects_unit_id'), 'interior_projects', ['unit_id'], unique=False)
    op.create_table('service_tickets',
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raised_on', sa.Date(), nullable=False),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('assigned_employee_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tickets_assigned_employee_id'), 'service_tickets', ['assigned_employee_id'], unique=False)
    op.create_index(op.f('ix_service_tickets_category'), 'service_tickets', ['category'], unique=False)
    op.create_index(op.f('ix_service_tickets_created_at'), 'service_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_tickets_customer_id'), 'service_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_tickets_raised_on'), 'service_tickets', ['raised_on'], unique=False)
    op.create_index(op.f('ix_service_tickets_status'), 'service_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_service_tickets_unit_id'), 'service_tickets', ['unit_id'], unique=False)
    op.create_table('cp_commissions',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('channel_partner_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['channel_partner_id'], ['channel_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cp_commissions_booking_id'), 'cp_commissions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_cp_commissions_channel_partner_id'), 'cp_commissions', ['channel_partner_id'], unique=False)
    op.create_index(op.f('ix_cp_commissions_created_at'), 'cp_commissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_cp_commissions_due_on'), 'cp_commissions', ['due_on'], unique=False)
    op.create_table('demands',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('plan_milestone_id', sa.Uuid(), nullable=False),
    sa.Column('construction_milestone_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('raised_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reminders_sent', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['construction_milestone_id'], ['construction_milestones.id'], ),
    sa.ForeignKeyConstraint(['plan_milestone_id'], ['plan_milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demands_booking_id'), 'demands', ['booking_id'], unique=False)
    op.create_index(op.f('ix_demands_construction_milestone_id'), 'demands', ['construction_milestone_id'], unique=False)
    op.create_index(op.f('ix_demands_created_at'), 'demands', ['created_at'], unique=False)
    op.create_index(op.f('ix_demands_due_on'), 'demands', ['due_on'], unique=False)
    op.create_index(op.f('ix_demands_plan_milestone_id'), 'demands', ['plan_milestone_id'], unique=False)
    op.create_index(op.f('ix_demands_raised_on'), 'demands', ['raised_on'], unique=False)
    op.create_index(op.f('ix_demands_status'), 'demands', ['status'], unique=False)
    op.create_table('home_loans',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(length=60), nullable=False),
    sa.Column('sanctioned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_loans_bank'), 'home_loans', ['bank'], unique=False)
    op.create_index(op.f('ix_home_loans_booking_id'), 'home_loans', ['booking_id'], unique=False)
    op.create_index(op.f('ix_home_loans_created_at'), 'home_loans', ['created_at'], unique=False)
    op.create_index(op.f('ix_home_loans_status'), 'home_loans', ['status'], unique=False)
    op.create_table('receipts',
    sa.Column('demand_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('from_bank_loan', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_created_at'), 'receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_receipts_demand_id'), 'receipts', ['demand_id'], unique=False)
    op.create_index(op.f('ix_receipts_received_on'), 'receipts', ['received_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_received_on'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_demand_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_created_at'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_home_loans_status'), table_name='home_loans')
    op.drop_index(op.f('ix_home_loans_created_at'), table_name='home_loans')
    op.drop_index(op.f('ix_home_loans_booking_id'), table_name='home_loans')
    op.drop_index(op.f('ix_home_loans_bank'), table_name='home_loans')
    op.drop_table('home_loans')
    op.drop_index(op.f('ix_demands_status'), table_name='demands')
    op.drop_index(op.f('ix_demands_raised_on'), table_name='demands')
    op.drop_index(op.f('ix_demands_plan_milestone_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_due_on'), table_name='demands')
    op.drop_index(op.f('ix_demands_created_at'), table_name='demands')
    op.drop_index(op.f('ix_demands_construction_milestone_id'), table_name='demands')
    op.drop_index(op.f('ix_demands_booking_id'), table_name='demands')
    op.drop_table('demands')
    op.drop_index(op.f('ix_cp_commissions_due_on'), table_name='cp_commissions')
    op.drop_index(op.f('ix_cp_commissions_created_at'), table_name='cp_commissions')
    op.drop_index(op.f('ix_cp_commissions_channel_partner_id'), table_name='cp_commissions')
    op.drop_index(op.f('ix_cp_commissions_booking_id'), table_name='cp_commissions')
    op.drop_table('cp_commissions')
    op.drop_index(op.f('ix_service_tickets_unit_id'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_status'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_raised_on'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_customer_id'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_created_at'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_category'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_assigned_employee_id'), table_name='service_tickets')
    op.drop_table('service_tickets')
    op.drop_index(op.f('ix_interior_projects_unit_id'), table_name='interior_projects')
    op.drop_index(op.f('ix_interior_projects_stage'), table_name='interior_projects')
    op.drop_index(op.f('ix_interior_projects_designer_employee_id'), table_name='interior_projects')
    op.drop_index(op.f('ix_interior_projects_customer_id'), table_name='interior_projects')
    op.drop_index(op.f('ix_interior_projects_created_at'), table_name='interior_projects')
    op.drop_table('interior_projects')
    op.drop_index(op.f('ix_customer_interactions_occurred_at'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_needs_reply'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_employee_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_created_at'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_bookings_unit_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_plan_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_employee_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_channel_partner_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booked_on'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_site_visits_status'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_scheduled_at'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_project_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_lead_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_employee_id'), table_name='site_visits')
    op.drop_index(op.f('ix_site_visits_created_at'), table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index(op.f('ix_lead_activities_occurred_at'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_employee_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_created_at'), table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_customers_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_rm_employee_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_lead_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_nri'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_units_unit_no'), table_name='units')
    op.drop_index(op.f('ix_units_tower_id'), table_name='units')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_project_id'), table_name='units')
    op.drop_index(op.f('ix_units_created_at'), table_name='units')
    op.drop_index(op.f('ix_units_config'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_owner_employee_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_on'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_severity'), table_name='risks')
    op.drop_index(op.f('ix_risks_rule_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_owner_employee_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_created_at'), table_name='risks')
    op.drop_index(op.f('ix_risks_category'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_quality_issues_tower_id'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_status'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_raised_on'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_owner_employee_id'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_created_at'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_contractor_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_preferred_project_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_employee_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_channel_partner_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_employee_targets_period_start'), table_name='employee_targets')
    op.drop_index(op.f('ix_employee_targets_employee_id'), table_name='employee_targets')
    op.drop_index(op.f('ix_employee_targets_created_at'), table_name='employee_targets')
    op.drop_table('employee_targets')
    op.drop_index(op.f('ix_construction_milestones_type'), table_name='construction_milestones')
    op.drop_index(op.f('ix_construction_milestones_tower_id'), table_name='construction_milestones')
    op.drop_index(op.f('ix_construction_milestones_planned_date'), table_name='construction_milestones')
    op.drop_index(op.f('ix_construction_milestones_owner_employee_id'), table_name='construction_milestones')
    op.drop_index(op.f('ix_construction_milestones_created_at'), table_name='construction_milestones')
    op.drop_index(op.f('ix_construction_milestones_contractor_id'), table_name='construction_milestones')
    op.drop_table('construction_milestones')
    op.drop_index(op.f('ix_towers_project_id'), table_name='towers')
    op.drop_index(op.f('ix_towers_created_at'), table_name='towers')
    op.drop_table('towers')
    op.drop_index(op.f('ix_safety_incidents_project_id'), table_name='safety_incidents')
    op.drop_index(op.f('ix_safety_incidents_occurred_on'), table_name='safety_incidents')
    op.drop_index(op.f('ix_safety_incidents_created_at'), table_name='safety_incidents')
    op.drop_table('safety_incidents')
    op.drop_index(op.f('ix_project_budgets_project_id'), table_name='project_budgets')
    op.drop_index(op.f('ix_project_budgets_created_at'), table_name='project_budgets')
    op.drop_table('project_budgets')
    op.drop_index(op.f('ix_price_history_project_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_effective_from'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_created_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_plan_milestones_payment_plan_id'), table_name='plan_milestones')
    op.drop_index(op.f('ix_plan_milestones_created_at'), table_name='plan_milestones')
    op.drop_table('plan_milestones')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_role_title'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_created_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_payment_plans_created_at'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_contractors_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_created_at'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_channel_partners_firm_name'), table_name='channel_partners')
    op.drop_index(op.f('ix_channel_partners_created_at'), table_name='channel_partners')
    op.drop_table('channel_partners')
    # ### end Alembic commands ###
